### ISSUE TITLE
'OEGridView' can't convert String into Integer 

### ISSUE THREAD

**Issue by kfihihc** [sonoramac/Podspecs#2]
### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.16.1
        Ruby : ruby 1.9.3p374 (2013-01-15 revision 38858) [x86_64-darwin12.2.0]
    RubyGems : 1.8.25
        Host : Mac OS X 10.8.2 (12C60)
       Xcode : 4.5.2 (4G2008a)
Ruby lib dir : /usr/local/Cellar/ruby/1.9.3-p374/lib
Repositories : Sonora-Podspecs - git://github.com/sonoramac/Podspecs.git @ 46168cc4d66a8ba4689e8cfd0c622be0b0fe3919
               master - https://github.com/CocoaPods/Specs.git @ 800013da202b3a1399dfb0ad65498423ef7395fc
```

### Podfile

```ruby
          platform :osx, '10.7'

pod 'MASShortcut'
pod 'DBPrefsWindowController'
pod 'SPMediaKeyTap'
pod 'INAppStoreWindow', :git => 'git://github.com/sonoramac/INAppStoreWindow.git'
pod 'AFNetworking', '1.0RC2'
pod 'INKeychainAccess'
pod 'HIDRemoteSDK'
pod 'OEGridView'
```

### Error

```
can't convert String into Integer
/Users/xiaobo/.cocoapods/Sonora-Podspecs/OEGridView/1.0.0/OEGridView.podspec:16:in `[]'
/Users/xiaobo/.cocoapods/Sonora-Podspecs/OEGridView/1.0.0/OEGridView.podspec:16:in `block in post_install'
/Users/xiaobo/.cocoapods/Sonora-Podspecs/OEGridView/1.0.0/OEGridView.podspec:14:in `each'
/Users/xiaobo/.cocoapods/Sonora-Podspecs/OEGridView/1.0.0/OEGridView.podspec:14:in `post_install'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.16.1/lib/cocoapods/installer.rb:157:in `block (2 levels) in run_post_install_hooks'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.16.1/lib/cocoapods/installer.rb:156:in `each'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.16.1/lib/cocoapods/installer.rb:156:in `block in run_post_install_hooks'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.16.1/lib/cocoapods/installer.rb:155:in `each'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.16.1/lib/cocoapods/installer.rb:155:in `run_post_install_hooks'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.16.1/lib/cocoapods/installer.rb:127:in `block (2 levels) in install!'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.16.1/lib/cocoapods/user_interface.rb:77:in `message'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.16.1/lib/cocoapods/installer.rb:125:in `block in install!'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.16.1/lib/cocoapods/user_interface.rb:37:in `section'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.16.1/lib/cocoapods/installer.rb:112:in `install!'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.16.1/lib/cocoapods/command/install.rb:46:in `run_install_with_update'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.16.1/lib/cocoapods/command/install.rb:51:in `run'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.16.1/lib/cocoapods/command.rb:75:in `run'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.16.1/bin/pod:16:in `<top (required)>'
/usr/local/opt/ruby/bin/pod:23:in `load'
/usr/local/opt/ruby/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by Keithbsmiley** [comment]
This seems to be obsolete.
